name: Update Fork
on:
  schedule:
    -  cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: linux-test-project
          base: master
          head: master
